### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by dawidwoz** [aske-w/itu-minitwit#87]
As a representative of group K, I created an issue connected with the security task that we had (Lecture 9). There is a list of what we found:
1. There is no SSL certificate. So the communication between your users and server can be manipulated along the way.
2. You don't have any enforced rules for passwords. Users may choose very weak passwords.
3. You don't limit tries to log in, so you can be bruteforced. 

Have a nice day and happy coding! 🙂

**Comment by xWermuth** [comment]
Noted. Thank you! :)
